[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

#[[plugins]]
#repo = 'honza/vim-snippets'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rs'

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = 'rs'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']
